spring.config.import=optional:file:../../.env[.properties]

spring.application.name=user-service
server.port=8443

# SSL Configuration
server.ssl.enabled=${SSL_ENABLED:false}
server.ssl.key-store=${SSL_KEYSTORE:/etc/ssl/user-service.p12}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:mazad-ssl-password}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=user-service

spring.datasource.url=${DB_URL}/${USER_DB_NAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
item.updated.topic=${ITEM_UPDATED_TOPIC}
item.created.topic=${ITEM_CREATED_TOPIC}
notify.friends.topic=${NOTIFY_FRIENDS_TOPIC}
friend.request.topic=${FRIEND_REQUEST_TOPIC}


auth-user.sync.topic=${USER_AUTH_SYNC_TOPIC}

user.default.avatar=${AVATAR_URL}
user.default.thumbnail=${AVATAR_THUMBNAIL_URL}
admin.password=${ADMIN_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true
