server:
  port: ${NOTIFICATION_SERVICE_PORT:8443}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE:/etc/ssl/notification-service.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:mazad-ssl-password}
    key-store-type: PKCS12
    key-alias: notification-service
cors:
  allowed-origins: ${ALLOWED_ORIGINS}
spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL}/${NOTIFICATION_DB_NAME} 
    username: ${NOTIFICATION_DB_USER}
    password: ${NOTIFICATION_DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka-c:9093}
    topics:
      bid-events: ${AUCTION_UPDATE_TOPIC:auction.update}
      chat-events: ${CHAT_UPDATE_TOPIC:chat-messages-topic}
      friends-events: ${NOTIFY_FRIENDS_TOPIC:notify.friends}
      friend-request-events: ${FRIEND_REQUEST_TOPIC:friend.request}
    consumer:
      group-id: ${KAFKA_GROUP_ID:notification-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer