services:
  # ============== FRONTEND ==============
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_KEY=${API_KEY}
        - VITE_MAZAD_IP=${MAZAD_IP}
        - VITE_DEFAUTLT_AVATAR=${AVATAR_URL}
        - VITE_DEFAUTLT_AVATAR_THUMB=${AVATAR_THUMBNAIL_URL}
    container_name: frontend-c
    image: mazad-frontend
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/certs/generated/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
      - ./infrastructure/certs/generated/nginx.key:/etc/nginx/ssl/nginx.key:ro
      - ./infrastructure/certs/generated/mazad-root-ca.crt:/etc/nginx/ssl/mazad-root-ca.crt:ro
    networks:
      - mazad-network
    depends_on:
      - mazad-gateway
    restart: unless-stopped

  # ============== DATABASE ==============
  postgres:
    container_name: postgres-c
    image: postgres:latest
    volumes:
      - postgres-v:${PGDATA}
      - ./infrastructure/postgres/init-scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5000:5432"
    networks:
      mazad-network:
    restart: unless-stopped
    env_file: .env
#
  redis:
    container_name: redis-c
    image: redis:8.4.0-bookworm
    # ports:
    #   - "6379"
    networks:
      mazad-network:
    restart: unless-stopped


  mazad-gateway:
    build: ./backend/mazad-gateway/
    container_name: mazad-gateway-c
    image: mazad-gateway
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      # - ITEMS_SERVICE_PORT=${ITEMS_SERVICE_PORT}
      - API_KEY=${API_KEY}
      # - AUTH_SERVER_PORT=${AUTH_SERVER_PORT}
      # - USER_SERVER_PORT=${USER_SERVER_PORT}
      # - BIDDING_SERVICE_PORT=${BIDDING_SERVICE_PORT}
      - FRONT_URL=${FRONT_URL}
      # SSL Configuration
      - SSL_ENABLED=true
      - SSL_KEYSTORE=/etc/ssl/gateway.p12
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
      
      - JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/app/certs/mazad-truststore.p12 
        -Djavax.net.ssl.trustStorePassword=mazad-ssl-password 
        -Djavax.net.ssl.trustStoreType=PKCS12

    volumes:
      - ./infrastructure/certs/generated/gateway.p12:/etc/ssl/gateway.p12:ro
      - ./infrastructure/certs/generated/mazad-truststore.p12:/app/certs/mazad-truststore.p12
    # ports:
    #   - "8443:8443"
    networks:
      mazad-network:
    restart: on-failure
##
  items-service:
    build: ./backend/item-service/
    container_name: item-service-c
    image: items-service
    environment:
      - DB_URL=${DB_URL}/${ITEMS_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - ITEMS_SERVICE_PORT=${ITEMS_SERVICE_PORT}
      - ITEM_CREATED_TOPIC=${ITEM_CREATED_TOPIC}
      - ITEM_UPDATED_TOPIC=${ITEM_UPDATED_TOPIC}
      - AUCTION_UPDATE_TOPIC=${AUCTION_UPDATE_TOPIC}
      - ITEM_CANCELLED_TOPIC=${ITEM_CANCELLED_TOPIC}
      # SSL Configuration
      - SSL_ENABLED=true
      - SSL_KEYSTORE=/etc/ssl/items-service.p12
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
    volumes:
      - ./infrastructure/certs/generated/items-service.p12:/etc/ssl/items-service.p12:ro
    depends_on:
      - postgres
      - mazad-gateway
      - kafka-service
    networks:
      mazad-network:
    restart: on-failure


  bidding-service:
    image: bidding-service-img:1
    build: ./backend/bidding-service/
    container_name: bidding-service
    environment:
     - DB_URL=${DB_URL}
     - DB_NAME=${BID_DB_NAME}
     - DB_USER=${BID_DB_USER}
     - DB_PASSWORD=${BID_DB_PASSWORD}
    #  - BIDDING_SERVICE_PORT=${BIDDING_SERVICE_PORT}
     - AUCTION_UPDATE_TOPIC=${AUCTION_UPDATE_TOPIC}
     - ITEM_CREATED_TOPIC=${ITEM_CREATED_TOPIC}
     - ITEM_UPDATED_TOPIC=${ITEM_UPDATED_TOPIC}
     # SSL Configuration
     - SSL_ENABLED=true
     - SSL_KEYSTORE=/etc/ssl/bidding-service.p12
     - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
    volumes:
      - ./infrastructure/certs/generated/bidding-service.p12:/etc/ssl/bidding-service.p12:ro
    depends_on:
      - postgres
      - mazad-gateway
      - kafka-service
    networks:
      mazad-network:
    restart: on-failure

  auth-service:
    build: ./backend/auth-service/
    container_name: auth-service
    image: auth-service-img
    depends_on:
      - postgres
      - mazad-gateway
    environment:
      - DB_URL=${DB_URL}
      - MAZAD_IP=${MAZAD_IP}
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - AUTH_SERVER_PORT=${AUTH_SERVER_PORT}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - ACCESS_TOKEN_MIN=${ACCESS_TOKEN_MIN}
      - REFRESH_TOKEN_DAY=${REFRESH_TOKEN_DAY}
      # kafka
      - USER_AUTH_SYNC_TOPIC=${USER_AUTH_SYNC_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=kafka-service:9093
      # - USER_SERVICE_URL=${USER_SERVICE_URL}
      # SSL Configuration
      - SSL_ENABLED=true
      - SSL_KEYSTORE=/etc/ssl/auth-service.p12
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
      - FORTY_TWO_CLIENT_ID=${FORTY_TWO_CLIENT_ID}
      - FORTY_TWO_CLIENT_SECRET=${FORTY_TWO_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      # - JAVA_TOOL_OPTIONS="-Djavax.net.ssl.trustStore=/app/certs/mazad-truststore.p12 -Djavax.net.ssl.trustStorePassword=mazad-ssl-password -Djavax.net.ssl.trustStoreType=PKCS12"
      # --- OUTBOUND: The Truststore (VIP List) ---
#      - JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/app/certs/mazad-truststore.p12
#        -Djavax.net.ssl.trustStorePassword=mazad-ssl-password
#        -Djavax.net.ssl.trustStoreType=PKCS12
    develop:
      watch:
        - action: rebuild
          path: ./backend/auth-service/src
        - action: rebuild
          path: ./backend/auth-service/pom.xml
        - action: sync
          path: ./backend/auth-service/src/main/resources
          target: /app/resources
          # Syncing resources (like application.properties) is instant
    volumes:
      - ./infrastructure/certs/generated/auth-service.p12:/etc/ssl/auth-service.p12:ro
      - ./infrastructure/certs/generated/mazad-truststore.p12:/app/certs/mazad-truststore.p12
    networks:
      mazad-network:
    restart: on-failure

  user-service:
    build: ./backend/user-service/
    container_name: user-service
    image: user-service-img
    depends_on:
      - postgres
      - mazad-gateway
      - kafka-service
    environment:
      - DB_URL=${DB_URL}
      - USER_DB_NAME=${USER_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - USER_SERVER_PORT=${USER_SERVER_PORT}
      - AVATAR_URL=${AVATAR_URL}
      - AVATAR_THUMBNAIL_URL=${AVATAR_THUMBNAIL_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      # kafka env
      - ITEM_CREATED_TOPIC=${ITEM_CREATED_TOPIC}
      - ITEM_UPDATED_TOPIC=${ITEM_UPDATED_TOPIC}
      - NOTIFY_FRIENDS_TOPIC=${NOTIFY_FRIENDS_TOPIC}
      - USER_AUTH_SYNC_TOPIC=${USER_AUTH_SYNC_TOPIC}
      - FRIEND_REQUEST_TOPIC=${FRIEND_REQUEST_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=kafka-service:9093
      # SSL Configuration
      - SSL_ENABLED=true
      - SSL_KEYSTORE=/etc/ssl/user-service.p12
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
    volumes:
      - ./infrastructure/certs/generated/user-service.p12:/etc/ssl/user-service.p12:ro
     
    networks:
      mazad-network:
    restart: on-failure


  kafka-service:
    container_name: kafka-c
    image: apache/kafka:latest
    # ports:
    #   - "${KAFKA_SERVICE_PORT}:${KAFKA_SERVICE_PORT}"
    environment:
      KAFKA_NODE_ID: 1 # unique id for this kafka node

      KAFKA_PROCESS_ROLES: broker,controller # defines the role of this node

      KAFKA_LISTENERS: >
        BROKER://0.0.0.0:9092,
        CLIENT://0.0.0.0:9093,
        CONTROLLER://0.0.0.0:9094

      KAFKA_ADVERTISED_LISTENERS: >
        CLIENT://kafka-service:9093,
        BROKER://kafka-service:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        BROKER:PLAINTEXT,
        CLIENT:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-service:9094

      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
      mazad-network:
    restart: on-failure


  minio:
    image: minio/minio:latest
    container_name: mazad-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BROWSER: "off"
    networks:
      - mazad-network
    volumes:
      - minio_data:/data
      - ./infrastructure/certs/generated/minio.crt:/root/.minio/certs/public.crt:ro
      - ./infrastructure/certs/generated/minio.key:/root/.minio/certs/private.key:ro
    command: server /data

    healthcheck:
          test: ["CMD", "curl", "-fk", "https://localhost:9000/minio/health/live"]
          interval: 7s
          timeout: 6s
          retries: 10

  minio-setup:
    image: minio/mc:latest
    container_name: mazad-minio-setup
    environment:
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      AVATAR_NAME: ${AVATAR_NAME}
      AVATAR_URL: ${AVATAR_URL}
      AVATAR_THUMBNAIL_NAME: ${AVATAR_THUMBNAIL_NAME}
    networks:
      - mazad-network
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./infrastructure/minio-service/init-minio.sh:/usr/bin/init-minio.sh
      - ./infrastructure/certs/generated/mazad-root-ca.crt:/root/.mc/certs/CAs/public.crt
      - ${AVATAR_PATH}:/default-images
    entrypoint: ["/bin/sh", "/usr/bin/init-minio.sh"]


  chat-service:
    build: ./backend/chat-service/
    container_name: chat-service-c
    image: chat-service
    depends_on:
      - postgres
      - kafka-service
      - mazad-gateway
      - auth-service
    environment:
      # DATABASE ENV VARS ====
      - "DB_URL=${DB_URL}/${CHAT_SERVICE_DB_NAME}"
      - "DB_NAME=${CHAT_SERVICE_DB_NAME}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      # KAFKA ENV VARS
      - "KAFKA_SERVICE_PORT=${KAFKA_SERVICE_PORT}"
      # SSL Configuration
      - SSL_ENABLED=true
      - SSL_KEYSTORE=/etc/ssl/chat-service.p12
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
    volumes:
      - ./infrastructure/certs/generated/chat-service.p12:/etc/ssl/chat-service.p12:ro
    networks:
      - mazad-network
      


  upload-service:
    build: ./backend/upload-service
    container_name: upload-service-c
    image: upload-service:latest
    environment:
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_PUB_URL: ${MINIO_PUB_URL}
      MINIO_URL: https://mazad-minio:9000
      SIGHTENGINE_USER: ${SIGHTENGINE_USER}
      SIGHTENGINE_PASSWORD: ${SIGHTENGINE_PASSWORD}

      SSL_ENABLED: "true"
      SSL_KEYSTORE: /etc/ssl/upload-service.p12
      SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}

      JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/app/certs/mazad-truststore.p12 
        -Djavax.net.ssl.trustStorePassword=mazad-ssl-password 
        -Djavax.net.ssl.trustStoreType=PKCS12
    volumes:
      - ./infrastructure/certs/generated/upload-service.p12:/etc/ssl/upload-service.p12:ro
      - ./infrastructure/certs/generated/mazad-truststore.p12:/app/certs/mazad-truststore.p12
    networks:
      - mazad-network
    depends_on:
      minio-setup:
        condition: service_completed_successfully

  notification-service:
    build: ./backend/notification-service
    container_name: notification-service-c
    image: notification-service:latest
    environment:
      - NOTIFICATION_DB_USER=${NOTIFICATION_DB_USER}
      - NOTIFICATION_DB_PASSWORD=${NOTIFICATION_DB_PASSWORD}
      - NOTIFICATION_DB_NAME=${NOTIFICATION_DB_NAME}
      - AUCTION_UPDATE_TOPIC=${AUCTION_UPDATE_TOPIC}
      - NOTIFY_FRIENDS_TOPIC=${NOTIFY_FRIENDS_TOPIC}
      - FRIEND_REQUEST_TOPIC=${FRIEND_REQUEST_TOPIC}
      - DB_URL=${DB_URL}

      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      
      - SSL_ENABLED=true
      - SSL_KEYSTORE=/etc/ssl/notification-service.p12
      - SSL_KEYSTORE_PASSWORD=${SSL_KEYSTORE_PASSWORD}
    volumes:
      - ./infrastructure/certs/generated/notification-service.p12:/etc/ssl/notification-service.p12:ro
    networks:
      - mazad-network
    depends_on:
      - postgres
      - kafka-service

networks:
  mazad-network:
    name: mazad-network
    driver: bridge

volumes:
  postgres-v:
    name: postgres-v
  minio_data:





# keytool -import -alias mazad-ca \
#     -file /usr/local/share/ca-certificates/mazad-root-ca.crt \
#     -cacerts -storepass changeit -noprompt
