spring.application.name=upload-service
server.port=${UPLOAD_SERVICE_PORT:8443}

server.ssl.enabled=${SSL_ENABLED:false}
server.ssl.key-store=${SSL_KEYSTORE:/etc/ssl/upload-service.p12}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:mazad-ssl-password}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=upload-service


ssl.trust-cert=${SSL_TRUST_CERT:/etc/ssl/mazad-root-ca.crt}

minio.url=${MINIO_URL:https://mazad-minio:9000}
minio.pubUrl=${MINIO_PUB_URL:https://localhost:9000}/api/upload/minio
minio.bucket-name=${MINIO_BUCKET_NAME}
minio.use-insecure-trust-manager=true

minio.access-key=${MINIO_USER}
minio.secret-key=${MINIO_PASSWORD}

sightengine.api.user=${SIGHTENGINE_USER}
sightengine.api.secret=${SIGHTENGINE_PASSWORD}