#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $NOTIFACTION_DB_USER WITH PASSWORD '$NOTIFACTION_DB_PASSWORD';
    CREATE DATABASE $NOTIFACTION_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $NOTIFACTION_DB_NAME TO $NOTIFACTION_DB_USER;
EOSQL

# 2. Connect to the NEW database to fix the schema permissions
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$NOTIFACTION_DB_NAME" <<-EOSQL
    GRANT ALL ON SCHEMA public TO $NOTIFACTION_DB_USER;
EOSQL