#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" \
  -c "CREATE ROLE \"$NOTIFICATION_DB_USER\" LOGIN PASSWORD '$NOTIFICATION_DB_PASSWORD';"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" \
  -c "CREATE DATABASE \"$NOTIFICATION_DB_NAME\";"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" \
  -c "GRANT ALL PRIVILEGES ON DATABASE \"$NOTIFICATION_DB_NAME\" TO \"$NOTIFICATION_DB_USER\";"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$NOTIFICATION_DB_NAME" \
  -c "GRANT ALL ON SCHEMA public TO \"$NOTIFICATION_DB_USER\";"