spring.application.name=chat-service
server.port=${CHAT_SERVICE_PORT:8080}

# DB 
spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA 
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# Kafka
spring.kafka.bootstrap-servers=kafka-service:${KAFKA_SERVICE_PORT}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

chat.kafka.topic=chat-messages-topic
 
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

spring.kafka.producer.properties.spring.json.write-dates-as-timestamps=false


# # chat-service 
# CHAT_SERVICE_PORT=5555
# CHAT_SERVICE_DB_NAME=${CHAT_SERVICE_DB_NAME}

# CHAT_SERVICE_DB_USER=chat-service-db-user
# CHAT_SERVICE_DB_PASSWORD=P4ssword
